id = "aether"
name = "Aether"
version = "0.1.0"
schema_version = 1
authors = ["Leo Douglas"]
description = "Aether language support."
repository = "https://github.com/eiwa-lang/zed-extension"

[grammars.aether]
repository = "https://github.com/eiwa-lang/tree-sitter"
commit = "aea95c4e0cb524435172500022e39456c196a1fd"
